# github.com/go-task/task

version: '2'

tasks:
  clean:
    cmds:
    - rm *.json_test.go
  gen:
    cmds:
    - go run -tags=dev generate.go
  test:
    deps: [gen]
    cmds:
    - go test -coverpkg=github.com/n-go/simex -coverprofile=coverage.out
  cover:
    deps: [test]
    cmds:
    - go tool cover -html=coverage.out
